usecase-beta
actor Admin("Admin")
actor auteur("auteur")
actor visiteur("visiteur")
system["blog"]
Admin--gére le contenu--system
auteur--rédige et gére les artcicles--system
visiteur--Consulte les articles publiés--system
