sequenceDiagram
    actor auteur
    participant system_blog

    auteur->>system_blog: acceder a ajouter un article
    system_blog-->>auteur: afficher un formulaire

    auteur->>system_blog: remplir les infos (titre-contenu-category-status-image..) et cliquer sur enregistrer

    alt le contenu est vide
        system_blog-->>auteur: refuser l'enregistrement avec message d'erreur (le contenu est obligatoire)

    else status est brouillon
        system_blog-->>auteur: enregistrer l'article dans la DB sous forme de brouillon et rediriger vers la liste des articles

    else cas nominal
        system_blog-->>auteur: enregistrer l'article et rediriger vers la liste des articles
    end